In [1]:
import numpy as np



In [2]:

A = np.array([[2, 4, 6], [1, 3, 5], [7, 9, 11]])
B = np.array([[8, 5, 2], [7, 4, 1], [6, 3, 0]])



In [3]:

sum_matrix = A + B



In [5]:

product_matrix = A * B



In [6]:

dot_product = np.dot(A, B.T)



In [7]:

determinant_A = np.linalg.det(A)

print(f"Element-wise Sum:\n{sum_matrix}")
print(f"Element-wise Product:\n{product_matrix}")
print(f"Dot Product:\n{dot_product}")
print(f"Determinant of A: {determinant_A}")


Element-wise Sum:
[[10  9  8]
 [ 8  7  6]
 [13 12 11]]
Element-wise Product:
[[16 20 12]
 [ 7 12  5]
 [42 27  0]]
Dot Product:
[[ 48  36  24]
 [ 33  24  15]
 [123  96  69]]
Determinant of A: 0.0
